version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - BUCKET=$(aws ssm get-parameter --name "/dnd-ui/${ENVIRONMENT}/bucket-name" --query "Parameter.Value" --output text)
      - DIST_ID=$(aws ssm get-parameter --name "/dnd-ui/${ENVIRONMENT}/distribution-id" --query "Parameter.Value" --output text)
      - aws s3 sync dist/ s3://${BUCKET} --delete
      - aws cloudfront create-invalidation --distribution-id ${DIST_ID} --paths "/*"
