export const ROUTES = {
  home: "/",
  characters: "/characters",
  createCharacter: "/characters/create",
  characterDetail: (id: number | string) => `/characters/${id}`,
  items: "/items",
  itemDetail: (id: number | string) => `/items/${id}`,
  monsters: "/monsters",
  monsterDetail: (id: number | string) => `/monsters/${id}`,
  notFound: "/404",
  login: "/login",
  signUp: "/sign-up",
  confirmSignUp: "/confirm-sign-up",
  forgotPassword: "/forgot-password",
} as const;
